Add: Views
lukman155/blog-rails pull request #6
Opened 2023-03-16 08:35 UTC by lukman155

Use preprocessed HTML file with embedded Ruby code.
Use layouts and templates for shared content.

2023-03-16 09:21 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @lukman155,

Good job so far!
✔️ Good documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 09:21 UTC, TedLivist commented on app/views/users/show.html.erb
> +    </button>
- [ ] Kindly use the `query_posts` method in your User model to fetch the recent posts of a user and render them in this User show page.

  ![image](https://user-images.githubusercontent.com/36542986/225561573-8ebf642b-0c35-4047-895d-81b7479aabc2.png)

- [ ] **[OPTIONAL]** I think your implementation of `query_posts` in the User model is incorrect. It fetches the recent posts regardless of the author. We should only fetch the posts that belong to the user. The `Post` uses all the records in the posts table, while `posts` uses only the posts belonging to the related author

  ```
  def query_posts
    posts.order(created_at: :desc).limit(3)
  end
  ```

2023-03-16 09:21 UTC, TedLivist commented on app/views/posts/index.html.erb
> +      <% end %>
- [ ] We should use the `query_comments` method in the Post model to render the recent comments of the post.

  ![image](https://user-images.githubusercontent.com/36542986/225562811-d08e85b3-a7ea-4167-8c10-2d859de6cafd.png)

2023-03-16 09:21 UTC, TedLivist commented on app/views/users/index.html.erb
> +</html>
- [ ] Kindly ensure your User index page matches the design.

  Your Implementation | Wireframe
  :---:|:---:
  ![irorrr](https://user-images.githubusercontent.com/36542986/225568519-1ba107aa-f91e-4095-9c9c-a2ca5f4685b6.jpg) | ![prprr](https://user-images.githubusercontent.com/36542986/225568509-6feb7d6b-3f91-4fbe-941f-af97c38cfdf5.jpg)

2023-03-16 09:21 UTC, TedLivist commented on app/views/users/show.html.erb
> +   <h1>Here is the list of Users<h1/>
- [ ] Kindly remove this text from the User show page.

2023-03-16 09:21 UTC, TedLivist commented on app/views/users/show.html.erb
> +</html>
- [ ] Kindly ensure this User show page matches the wireframe.

  Your Implementation | Wireframe
  :---:|:---:
  ![ifffo](https://user-images.githubusercontent.com/36542986/225569086-4a07d843-0a1b-4fe1-b241-1cdd4aa543f6.jpg) | ![ofoff](https://user-images.githubusercontent.com/36542986/225569097-f1af87cc-ab76-404e-a4ef-e7c2ac9c3e04.jpg)

2023-03-16 09:21 UTC, TedLivist commented on app/views/posts/index.html.erb
> +</html>
- [ ] Kindly ensure the Post index page matched the wireframe.

  Your Implementation | Wireframe
  :---:|:---:
  ![liee](https://user-images.githubusercontent.com/36542986/225569876-7a5942f8-1453-4e9e-9705-2e0d4380351b.jpg) | ![oeye](https://user-images.githubusercontent.com/36542986/225569892-34cef474-18ee-401c-8d7c-cce0b7c2309d.jpg)

2023-03-16 09:21 UTC, TedLivist commented on app/views/posts/show.html.erb
> +    <% @post.query_comments.each do |comment| %>
- [ ] I was unable to create a comment so I am unable to view this page in its entirety. Kindly look into your Comment migrations. There is no `post_id` in the table. Additionally, you have `user_id` and `author_id` which are redundant. From a previous project, you were supposed to have `author_id` and `post_id`.

  ![image](https://user-images.githubusercontent.com/36542986/225566995-29603203-8abb-4e9b-92ae-29a95c4aa15f.png)
  <hr/>
  
  ![image](https://user-images.githubusercontent.com/36542986/225571897-f07d43fb-6b20-4c65-9739-56b383f963cc.png)

2023-03-16 09:21 UTC, TedLivist commented on app/views/posts/show.html.erb
> +</html>
- [ ] I had to comment out parts of the HTML related to comments. Kindly ensure your Post show page matches the wireframe.

  Your Implementation | Wireframe
  :---:|:---:
  ![irirro](https://user-images.githubusercontent.com/36542986/225571382-fd4f39b6-772d-41d3-9ab5-6b4c05f74a92.jpg) | ![ooprr](https://user-images.githubusercontent.com/36542986/225571357-801edc33-1d76-4725-a44a-bad34aec501e.jpg)

2023-03-17 15:57 UTC, mckent05 requested changes
Hi @lukman155, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 15:57 UTC, mckent05 commented on app/views/posts/show.html.erb
> +</html>
- Just as the previous reviewer suggested please ensure your project matches the wireframe. When viewing the post show page, I should be able to see all comments and the author/user that made the comment.

Your project:
![wrvqwrvqr](https://user-images.githubusercontent.com/73607512/225954120-aa6a5579-32a9-488e-a649-fdbf066cc0b2.PNG)

2023-03-17 15:57 UTC, mckent05 commented on app/views/users/index.html.erb
> +</html>
- Just as the previous reviewer suggested please ensure your project's styling matches the wireframe. The profile picture fr each user should be aligned on the left while the username name is aligned n the right. Please fix this 👍 👍 

Your project:
![zdgnzdgn](https://user-images.githubusercontent.com/73607512/225954798-bd6fcf6b-f0b6-4898-b715-c6466d681334.PNG)

2023-03-17 15:57 UTC, mckent05 commented on app/views/posts/index.html.erb
> +</html>
**OPTIONAL** - This page should show the list of all posts for a user and the 3 most recent comments. Please fix this 🙏 

Your project:
![dfdf](https://user-images.githubusercontent.com/73607512/225955788-8bb9f154-8ff3-4ab4-894c-85a3f9791320.PNG)

2023-03-18 12:11 UTC, brytebee approved these changes
Hi, @lukman155👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great work implementing the design and other suggested changes.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 12:12 UTC, merged